---
title: "R Notebook"
output: html_notebook
---
 
Basic finctions
```{r}
library(igraph)
library(TDAmapper)
library(fastcluster)
library(FactoMineR)
library(ggplot2)
#devtools::install_github("christophergandrud/networkD3")
library(networkD3)

range01 <- function(x)(x-min(x))/diff(range(x))
cRamp <- function(x){
  cols <- colorRamp(rainbow(7))(range01(x))
  apply(cols, 1, function(xt)rgb(xt[1], xt[2], xt[3], maxColorValue=255))
} 

listintolengths <- function(x,nodeScale = 3){
  a <- c()
  for(item in x){
    a <- c(a, (nodeScale)*log(length(item) + 1))
  }
  return(a)
}

#coloring Vertices
#Method: mean of points marked by players in the vertex
meanforcolor <- function(map, data){
  allpoints <- data$PTS
  normalCoeff <- 255./max(allpoints)
  auxpoints <- map$points_in_vertex
  answer <- c()
  for(item in auxpoints){
    newitem <- unlist(item)
    num <- mean(allpoints[newitem])
    answer <- c(answer, num)
  }
  return(answer)
}

#this is for plotting wiht network3d
meanforcolor2 <- function(map, data){
  allpoints <- data$PTS
  
  auxpoints <- map$points_in_vertex
  answer <- c()
  for(item in auxpoints){
    newitem <- unlist(item)
    num <- mean(allpoints[newitem])
    answer <- c(answer, num)
  }
  return(answer)
}
#coloring Vertices
#Method: most frequent position
mostFreqcolor <- function(map, labels){
  auxpoints <- map$points_in_vertex
  answer <- c()
  answer2 <- c()
  answer3 <- c()
  for(item in auxpoints){
    newitem <- unlist(item)
    
    num <- which.max(table(labels[newitem]))
    num2 <- max(table(labels[newitem]))
    num3 <- length(newitem)
    
    answer <- c(answer, num)
    answer2 <- c(answer2, num2)
    answer3 <- c(answer3, num3)
  }
  return(list(mostFreq = answer, freq = answer2, numPoints = answer3))
}

## This function computes and plots the mapper graph
MapperAndPlot <- function(distance_matrix, filter_values,
                          num_intervals, percent_overlap, num_bins) {
  map    <- mapper2D(
              distance_matrix = distance_matrix, 
              filter_values = filter_values,
              num_intervals = num_intervals,#20,20 or 30,30
              percent_overlap = percent_overlap,
              num_bins_when_clustering = num_bins # Explaining this parameter:
                # The cluster phase here is a hierarquical cluster. to define the
                # number of cluster from the hTree, we splite the real interval 
                # [0,max(height)] into num_bins_... intervals of the same size (that is 
                # if num_b... is 2, 2 intervals will be created, [0,max(height)/2) and 
                # [max(height)/2,max(height)]). We them take the clusters from the first 
                # interval, in deacrising order, that has no points (players) in it.
        )
  
  #plot
  g <- graph.adjacency(map$adjacency, mode="undirected")
  
  V(g)$color <- cRamp(meanforcolor(map,df))
  V(g)$size <- listintolengths(map$points_in_vertex)
  
  plot(g, layout = layout.auto(g), vertex.label = NA)
  #plot(g, layout = layout.auto(g), vertex.label.cex = .4)
}
```

This function recieves the cluster label and returns the players that are in that cluster
```{r}
clusterintoplayers <- function(data, map, label){
  players <- map$points_in_vertex[label]
  answer <- c()
  allplayers <- data$Player
  for(player in players){
    answer <- c(answer, toString(allplayers[player]))
  }
  return (answer)
}

#example:
#clusterintoplayers(df, map, 100)
```

trying Alagapans data
```{r}
#import data
df <- read.csv("../../Data/NBA-2011-data-With-Positions.csv")
df
# labels
label <- df$PosicAbbrev
#levels(label) <- c(5,4,1,3,2)

# features selection -> new smaller dataset -> distance matrix
chosen_features = c('REB','AST','TOV','STL','BLK','PF','PTS')
X <- as.matrix(df[chosen_features])

# normalizing according to total time played
X <- X/df$MIN

#Normalizing data: mean = 0
X <- t(t(X) - apply(X,2,mean))

### Calculating distance matrix - (3 metrics shown below)
## Normalized euclidian metric
#normX <- X/apply(X,1,function(x) sqrt(sum(x^2)))
#d <- dist(normX,method = "euclidian")
## Variance Normalized euclidian metric
normX <- t(t(X)/sqrt(diag(var(X)))) # dividing columns by the variance
                                    # (normalizing without centering)
d <- dist(normX,method = "euclidian") # This way I get what Alagapin called
                                      # "Variance normalized euclidean distance"
##Euclidian distance
#d <- dist(X,method = "euclidian")

#Taking filter function from PCA
myPCA <- PCA(normX,graph = F)
plot.PCA(myPCA,axes = c(1,2),choix = "var")
df_red = data.frame(myPCA$ind$coord)
#ggplot(df_red) + aes(x = Dim.1, y = Dim.2) + geom_point()
#plot.PCA(myPCA,axes = c(1,2),choix = "ind", col.ind = label, label = "ind.sup")

filter <- list(matrix(myPCA$ind$coord[,1]),matrix(myPCA$ind$coord[,2]))

#applying mapper
map    <- mapper2D(
          distance_matrix = d, 
          filter_values = filter,
          num_intervals = c(30,30),#20,20 or 30,30
          percent_overlap = 50,
          num_bins_when_clustering = 20 # Explaining this parameter:
              # The cluster phase here is a hierarquical cluster. to define the
              # number of cluster from the hTree, we splite the real interval 
              # [0,max(height)] into num_bins_... intervals of the same size (that is 
              # if num_b... is 2, 2 intervals will be created, [0, max(height)/2) and 
              # [max(height)/2,max(height)]). We them take the clusters from the first 
              # interval, in deacrising order, that has no points (players) in it.
      )

#plotting
g <- graph.adjacency(map$adjacency, mode="undirected")

V(g)$color <- cRamp(meanforcolor(map = map,data = df))
V(g)$size <- listintolengths(map$points_in_vertex, nodeScale = 3)
V(g)$label.cex = .15

tkplot(g, layout = layout.auto(g))

pdf("Alagapan3030-50-20-colorbyPoints.pdf")
plot(g, layout = layout.auto(g))
dev.off()


```


## trying our data
```{r}
#import data
df <- read.csv("../../Data/NBA-data-With-Positions.csv")
df
# labels
label <- df$PosicAbbrev
levels(label) <- c(5,4,1,3,2)

# features selection -> new smaller dataset -> distance matrix
chosen_features = c('REB','AST','TOV','STL','BLK','PF','PTS')
X <- as.matrix(df[chosen_features])

# normalizing according to total time played
X <- X/df$MIN

#Normalizing data: mean = 0
X <- t(t(X) - apply(X,2,mean))

### Calculating distance matrix - (3 metrics shown below)
## Normalized euclidian metric
#normX <- X/apply(X,1,function(x) sqrt(sum(x^2)))
#d <- dist(normX,method = "euclidian")
## Variance Normalized euclidian metric
normX <- t(t(X)/sqrt(diag(var(X)))) # dividing columns by the variance
                                    # (normalizing without centering)
d <- dist(normX,method = "euclidian") # This way I get what Alagapin called
                                      # "Variance normalized euclidean distance"
##Euclidian distance
#d <- dist(X,method = "euclidian")

#Taking filter function from PCA
myPCA <- PCA(normX,graph = F)
plot.PCA(myPCA,axes = c(1,2),choix = "var")

df_red = scale(myPCA$ind$coord)
ggplot(data.frame(df_red)) + aes(x = Dim.1, y = Dim.2) + geom_point(color = label)
plot.PCA(myPCA,axes = c(1,2),choix = "ind", col.ind = label, label = "ind.sup")

filter <- list(matrix(df_red[,1]),matrix(df_red[,2]))

#applying mapper
map    <- mapper2D(
          distance_matrix = d, 
          filter_values = filter,
          num_intervals = c(30,30),#20,20 or 30,30
          percent_overlap = 50,
          num_bins_when_clustering = 5 # Explaining this parameter:
              # The cluster phase here is a hierarquical cluster. to define the
              # number of cluster from the hTree, we splite the real interval 
              # [0,max(height)] into num_bins_... intervals of the same size (that is 
              # if num_b... is 2, 2 intervals will be created, [0, max(height)/2) and 
              # [max(height)/2,max(height)]). We them take the clusters from the first 
              # interval, in deacrising order, that has no points (players) in it.
      )

#plotting
g <- graph.adjacency(map$adjacency, mode="undirected")

V(g)$color <- cRamp(meanforcolor(map,df))
#V(g)$color <- cRamp(mostFreqcolor(map,labels = label)$mostFreq)
V(g)$size <- listintolengths(map$points_in_vertex, nodeScale = 4)
V(g)$label.cex = .15



#tkplot(g, layout = layout.auto(g))

pdf("Seas2015-3030-50-5-colorbyPoints.pdf")
plot(g, layout = layout.auto(g))
dev.off()


V(g)$color <- cRamp(mostFreqcolor(map,labels = label)$mostFreq)

#tkplot(g, layout = layout.auto(g))
 pdf("Seas2015-3030-50-5-colorbyPosic.pdf")
plot(g, layout = layout.auto(g))
dev.off()


# create data frames for vertices and edges with the right variable names 
MapperNodes <- mapperVertices(map, 1:dim(X)[1])
MapperLinks <- mapperEdges(map)

View(MapperNodes)
MapperNodes$Nodesize <- (100)*(MapperNodes$Nodesize)
unlist(MapperNodes$Nodename[11]) + 3
# interactive plot
forceNetwork(Nodes = MapperNodes, Links = MapperLinks, 
            Source = "Linksource", Target = "Linktarget",
            Value = "Linkvalue", NodeID = "Nodename",
            Nodesize = "Nodesize",Group = "Nodegroup",
            opacity = 0.8, linkDistance = 1, charge = -1000,
            zoom = T) %>% saveNetwork(file = 'Net1.html')


?forceNetwork
```








